# Generated by Django 3.0.8 on 2020-08-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subhead',
            field=models.CharField(default='Subheading', max_length=200),
            preserve_default=False,
        ),
    ]
