# Generated by Django 3.0.8 on 2020-08-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_auto_20200805_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetails',
            old_name='name',
            new_name='username',
        ),
    ]
