# Generated by Django 3.0.8 on 2020-08-05 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20200805_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetails',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
